[main]
plugins=keyfile
no-auto-default=*
dns=systemd-resolved
rc-manager=symlink

[ifupdown]
managed=true

[keyfile]
unmanaged-devices=

[device-widelapse]
match-device=interface-name:*
managed=1

[connectivity]
enabled=false
