[main]
plugins=keyfile
no-auto-default=*
# The policy daemon configures systemd-resolved without reapplying links.
dns=none
rc-manager=unmanaged

[ifupdown]
managed=true

[keyfile]
unmanaged-devices=

[device-widelapse]
match-device=interface-name:*
managed=1

[connectivity]
enabled=false
