[system]
compatible=widelapse-orangepizero3-ab-v1
bootloader=uboot
statusfile=/opt/widelapse/rauc/status.raucs
bundle-formats=plain
boot-attempts=3
boot-attempts-primary=3

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/disk/by-partuuid/574c4150-02
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partuuid/574c4150-03
type=ext4
bootname=B
