BOARD=orangepizero3
BRANCH=current
RELEASE=trixie
BUILD_DESKTOP=no
BUILD_MINIMAL=yes
KERNEL_CONFIGURE=no
HOST=widelapse
CONSOLE_AUTOLOGIN=no

# Requires the new factory partition layout
enable_extension widelapse-rauc

function user_config__widelapse_packages() {
    add_packages_to_image \
        net-tools \
        openssh-server \
        fail2ban
}
