#!/bin/bash
set -euo pipefail
mountpoint -q /opt/widelapse
actual=$(findmnt -n -o SOURCE --target /opt/widelapse)
[[ $(readlink -f "$actual") == /dev/mmcblk0p4 ]]
[[ $(blkid -s PARTUUID -o value /dev/mmcblk0p4) == 574c4150-04 ]]
